# Generated by Django 5.2.5 on 2025-08-29 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogpost",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("can_manage_blog", "Может управлять блогом"),
                    ("can_publish_blog_post", "Может публиковать записи блога"),
                    ("can_edit_any_blog_post", "Может редактировать любые записи блога"),
                    ("can_delete_any_blog_post", "Может удалять любые записи блога"),
                ],
                "verbose_name": "Запись блога",
                "verbose_name_plural": "Записи блога",
            },
        ),
    ]
