# Generated by Django 5.2.5 on 2025-08-28 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "permissions": [("can_unpublish_product", "Can unpublish product")],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец продукта",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="publish",
            field=models.CharField(
                choices=[
                    ("pending", "На модерации"),
                    ("published", "Опубликован"),
                    ("rejected", "Отказано в публикации"),
                    ("unpublished", "Снят с публикации"),
                ],
                default="pending",
                max_length=100,
                verbose_name="Статус публикации",
            ),
        ),
    ]
