# Generated by Django 5.2.4 on 2025-08-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_category_description_alter_category_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        help_text="Официальное название компании",
                        max_length=200,
                        verbose_name="Название компании",
                    ),
                ),
                (
                    "address",
                    models.TextField(help_text="Полный адрес компании", verbose_name="Адрес"),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="Контактный телефон в формате +7 (XXX) XXX-XX-XX",
                        max_length=20,
                        verbose_name="Телефон",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Электронная почта для связи",
                        max_length=254,
                        verbose_name="Email",
                    ),
                ),
                (
                    "working_hours",
                    models.CharField(
                        help_text="Например: Пн-Пт: 9:00-18:00, Сб-Вс: выходной",
                        max_length=100,
                        verbose_name="Часы работы",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Дополнительная информация о компании",
                        null=True,
                        verbose_name="Описание",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Отображать эту информацию на сайте",
                        verbose_name="Активно",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
            ],
            options={
                "verbose_name": "Контактная информация",
                "verbose_name_plural": "Контактная информация",
                "ordering": ["-created_at"],
            },
        ),
    ]
